repositories:
  - name: clbb-io
    url: https://github.com/your-org/clbb-io.git
    branch: master
  - name: clbb-remote-controller
    url: https://github.com/your-org/clbb-remote-controller.git
    branch: master
  - name: clbb-front
    url: https://github.com/your-org/clbb-front.git
    branch: master
  - name: clbb-projection
    url: https://github.com/your-org/clbb-projection.git
    branch: master