repositories:
  - name: clbb-io
    url: https://github.com/diegoalrv/clbb-io.git
    branch: v2
  - name: clbb-remote-controller
    url: https://github.com/diegoalrv/clbb-remote-controller.git
    branch: v2
  - name: clbb-front
    url: https://github.com/diegoalrv/clbb-front.git
    branch: v2
  - name: clbb-projection
    url: https://github.com/diegoalrv/clbb-projection.git
    branch: v2